/*
Copyright 2025 The llm-d-inference-sim Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Contains structures and functions related to responses for all supported APIs
package llmdinferencesim

import (
	"encoding/json"
	"errors"
	"strings"
)

// completionResponse interface representing both completion response types (text and chat)
type completionResponse interface{}

// baseCompletionResponse contains base completion response related information
type baseCompletionResponse struct {
	// ID defines the response ID
	ID string `json:"id"`
	// Created defines the response creation timestamp
	Created int64 `json:"created"`
	// Model defines the Model name for current request
	Model string `json:"model"`
	// Usage contains the token usage statistics for the request
	Usage *usage `json:"usage"`
	// Object is the Object type, "text_completion", "chat.completion", or "chat.completion.chunk"
	Object string `json:"object"`
}

// usage contains token usage statistics
type usage struct {
	// PromptTokens is the number of tokens in the prompt
	PromptTokens int `json:"prompt_tokens"`
	// CompletionTokens is the number of tokens generated by the model as the response
	CompletionTokens int `json:"completion_tokens"`
	// TotalTokens is the total number of tokens processed for the request (the sum of the two values above)
	TotalTokens int `json:"total_tokens"`
}

// chatCompletionResponse defines structure of /chat/completion response
type chatCompletionResponse struct {
	baseCompletionResponse
	// Choices list of Choices of the response, according of OpenAI API
	Choices []chatRespChoice `json:"choices"`
}

// baseResponseChoice contains base completion response's choice related information
type baseResponseChoice struct {
	// Index defines completion response choise Index
	Index int `json:"index"`
	// FinishReason defines finish reason for response or for chunks, for not last chinks is defined as null
	FinishReason *string `json:"finish_reason"`
}

// v1/chat/completion
// message defines vLLM chat completion message
type message struct {
	// Role is the message Role, optional values are 'user', 'assistant', ...
	Role string `json:"role,omitempty"`
	// Content defines text of this message
	Content content `json:"content,omitempty"`
	// ToolCalls are the tool calls created by the model
	ToolCalls []toolCall `json:"tool_calls,omitempty"`
}

type content struct {
	Raw        string
	Structured []contentBlock
}

type contentBlock struct {
	Type     string     `json:"type"`
	Text     string     `json:"text,omitempty"`
	ImageURL ImageBlock `json:"image_url,omitempty"`
}

type ImageBlock struct {
	Url string `json:"url,omitempty"`
}

// UnmarshalJSON allow use both format
func (mc *content) UnmarshalJSON(data []byte) error {
	// Raw format
	var str string
	if err := json.Unmarshal(data, &str); err == nil {
		mc.Raw = str
		return nil
	}

	// Block format
	var blocks []contentBlock
	if err := json.Unmarshal(data, &blocks); err == nil {
		mc.Structured = blocks
		return nil
	}

	return errors.New("content format not supported")
}

func (mc content) MarshalJSON() ([]byte, error) {
	if mc.Raw != "" {
		return json.Marshal(mc.Raw)
	}
	if mc.Structured != nil {
		return json.Marshal(mc.Structured)
	}
	return json.Marshal("")
}

func (mc content) PlainText() string {
	if mc.Raw != "" {
		return mc.Raw
	}
	var sb strings.Builder
	for _, block := range mc.Structured {
		if block.Type == "text" {
			sb.WriteString(block.Text)
			sb.WriteString(" ")
		}
	}
	return sb.String()
}

// functionCall defines a tool call generated by the model including its arguments
type functionCall struct {
	// Arguments are the arguments of the function call
	Arguments string `json:"arguments,omitempty"`
	// Name is the function's name, can be null in streaming in not the first chunk
	Name *string `json:"name"`
}

// toolCall defines a tool call generated by the model
type toolCall struct {
	// Function is a tool call generated by the model
	Function functionCall `json:"function"`
	// ID is the ID of the tool call
	ID string `json:"id"`
	// Type is the type of the tool, only functions are supported
	Type string `json:"type"`
	// Index is the index of the tool in the sequence of tools generated by the model
	Index int `json:"index"`
}

// chatRespChoice represents a single chat completion response choise
type chatRespChoice struct {
	baseResponseChoice
	// Message contains choice's Message
	Message message `json:"message"`
}

// textCompletionResponse defines structure of /completion response
type textCompletionResponse struct {
	baseCompletionResponse
	// Choices list of Choices of the response, according of OpenAI API
	Choices []textRespChoice `json:"choices"`
}

// textRespChoice represents a single text completion response choise
type textRespChoice struct {
	baseResponseChoice
	// Text defines request's content
	Text string `json:"text"`
}

// completionRespChunk is an interface that defines a single response chunk
type completionRespChunk interface{}

// chatCompletionRespChunk is a single chat completion response chunk
type chatCompletionRespChunk struct {
	baseCompletionResponse
	// Choices list of Choices of the response, according of OpenAI API
	Choices []chatRespChunkChoice `json:"choices"`
}

// chatRespChunkChoice represents a single chat completion response choise in case of streaming
type chatRespChunkChoice struct {
	baseResponseChoice
	// Delta is a content of the chunk
	Delta message `json:"delta"`
}

// completionError defines the simulator's response in case of an error
type completionError struct {
	// Object is a type of this Object, "error"
	Object string `json:"object"`
	// Message is an error Message
	Message string `json:"message"`
	// Type is a type of the error
	Type string `json:"type"`
	// Params is the error's parameters
	Param *string `json:"param"`
	// Code is http status Code
	Code int `json:"code"`
}
