name: Markdown Link Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lychee:
    name: Check Markdown Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lychee v0.18.1
        run: |
          curl -Ls https://github.com/lycheeverse/lychee/releases/download/lychee-v0.18.1/lychee-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv lychee /usr/local/bin
      - name: Run lychee on Markdown files with config
        run: |
          find . -name "*.md" -print0 | xargs -0 lychee --config .lychee.toml --verbose --no-progress